#+TITLE: 安慰劑效應
#+DATE: <2017-07-26 Wed>
#+AUTHOR: Felix Chang(張昌衡)
#+EMAIL: felix.profecia@gmail.com
#+LANGUAGE: en
#+CREATOR: Emacs 25.2.1 (Org mode 9.0.9)

* 安慰劑效應
  安慰劑指的是「在沒有明顯物質介入的情況下，心理治療身體的力量。」有時候， 這種效應是由於服用假藥所引起的，通常，這些假藥是由對人體不起化學作用的物質 所製造的藥丸，這種藥丸被稱為安慰劑 —— 拉丁文的意思是「取悅」[fn:1]。
  每一次，有新藥或是新的療法在試驗時，都要和安慰劑做比較，如果效果比安慰劑還要好，那麼這個新藥或新的療法，才可以稱為是有療效的，因為安慰劑的效果是這麼的強大，使得醫學研究幾乎無法忽略他的存在，只能盡可能的排除它。所以我們得做隨機的雙盲實驗，甚至是三盲實驗。雙盲實驗要求實驗者或受試者都不知道實驗的內容，而三盲指的是連參與統計分析的人也不知道實驗的內容，這麼做的目的，是為了排除有人在有意或無意狀態下，對實驗中造成偏頗結果。
  例如，今天我發明了一顆治療高血壓的藥物，我想知道這顆藥物是真的有效，還是只是心理因素造成的安慰劑效應，那麼我就該設計一個實驗來排除心理因素以證明它有效。首先，我們得隨機地把受試的人分成兩組，一組接受安慰劑，另一組接受我發明的新藥，我不能讓受試者知道自己吃的是新藥或是安慰劑，以免干擾受試者的反應，但同時，我也必需讓參與實驗的操作人員，也不知道誰吃了新藥還是安慰劑。以免他們有意或無意的暗示了受試者，或者有意或無意的在報告中，回報較偏頗的結論。如果做的更深入一點，我會讓統計分析人員也不知道實驗的內容，以免他們做出不當的分析，回報偏差的結果。在這樣子的實驗設計下，如果我的新藥，仍然比安慰劑有更高的療效，那麼我就可以說，我發明的這顆新藥，是有療效的。
  從另一個角度來說，為什麼不能和沒有吃藥的人比呢，而必需得和吃安慰劑的人比？因為，我們無法對實驗操作人員或是受試者隱瞞他們有沒有吃藥，吃藥的人就是知道他們有吃藥，沒吃的就是知道他們沒吃，所以隨機雙盲在這種實驗設計中是做不到的，也因此，我們就無法知道藥效是來自於安慰劑效應還是來自於藥本身的化學作用，所以我們只好和安慰劑比，但即使如此，依然有盲點。
  一個受過有經驗且受過良好訓練的分析者，總是有辦法從分析之中猜出實驗的內容是什麼，要排除他們主觀的因素並不那麼的容易。再者，就算你不讓受試者知道自己吃了什麼東西，他們仍然可以從藥物的反應，直接引起安慰劑反應。也就是說，把副作用轉化成真正的藥效。更進一步，有研究指出，即使讓受試者知道自己吃的是安慰劑，受試者依然會出現安慰者的反應，也就是說，即使我知道我吃的只是澱粉，我依然可以因此而得到相對的療效。那麼我們到底排除了什麼呢?藥效真的是獨立於主觀的意識而超然的存在嗎?

  安慰劑效應的想法，不斷的在我的心裡徘徊，這讓我開始不斷的去檢視醫療理論所擁有的效力與醫療的本質。

  2002 年，新英格蘭醫學期刊上，刊登了一篇關於安慰劑外科手術的研究，研究者 隨機的把一群需要動膝關結手術的病人隨機分成三組，一組接受灌洗的手術，一組接 受進一步的清創手術，而最後一組只接受了安慰劑手術，也就是說，第三組的手術中， 病人只有皮膚被劃開一個小洞，但沒有做進一步的任何治療，神奇的是，這三個手術 帶來的結果，在統計上居然沒有任何的差別[fn:2]。這個論文的出現，讓我大感吃驚，就連開刀也同樣存在著安慰劑效應，更另人吃驚的是另一篇發表在《疼痛》的論文，該論文把一群下背痛的病人分成兩組，一組給予常規的治療，另一組給予常規的治療外，在加上安慰劑的藥物，但醫生很明確的讓患者知道，那只是一顆安慰劑。另人意外的 是，從這組加上安慰劑藥物的患者得到的結果，竟然比沒有服用安慰組的那一組還要好，後來研究者又讓沒有服用安慰劑的那一組，也服用安慰劑，結果患者的情況也明 顯的提升了[fn:3]。

  即使我們真的完全排除了安慰劑效應，得到了一個超然於主觀之外的真實藥效， 但卻依然無法阻止在治療的過程之中不斷發生的安慰劑效應，整個治療的過程中，人 的主觀都在場，醫生和病人的心理狀態都會對治療帶來許多不同的影響，甚至連檢查 本身都可能是一種治療。以 X 光為例，《英國醫學期刊》的一個研究指出，他們比較 入院進行 X 光檢查的 210 位與未照片子的 211 位下背痛患者，即使他們都接受了同樣 的醫療程序，但有照 X 光片的患者，雖然他們覺得有受到適當的治療，但卻沒有得到 多少效果，反而他們的疼痛還持續了更長的時間。其中的原因，可能可以歸咎於 X 光片，觀看受損的椎間盤催化了患者事態嚴重的觀感[fn:4]。這種以負面效果出現的安慰劑 效應，醫學上稱為 nocebo effect，中文譯作，反安慰劑效應。

  一個我親身經歷的例子，或許可以為檢查帶來的療效，做出最好的見證。
  #+BEGIN_QUOTE
  我的一個朋友因為背痛而向我抱怨了許多天，最終他終於受不了，請我陪他一起 去骨科看醫生，到了診間，他告訴醫生他的病情，醫生很仔細的檢查之後，就請他先 去照 X 光，然後再回到診間看結果。半個小時後，結果出來了，我們又被醫生叫進診 間，醫生看著我的朋友，笑笑的把 X 光片拿出來，以一種極為輕鬆且愉快的口吻指著 X 光片說，「這是我看過最漂亮的脊椎了，看看這個漂亮的弧形，你的腰沒有問題。」 我的朋友聽了，驚訝的不得了，而同時，他的下背居然馬上就不痛了。
  #+END_QUOTE


  那麼，我們究竟如何在整個醫療的過程中，除掉安慰劑效應呢?我想引用威廉. 詹姆士的一句話來為這個段落做個總結，他說，「科學說應該壓抑經驗中自我的因 素，這實在很荒謬。現實的主軸到處是自我的立場，這些立場就像串在現實軸線上的 念珠一樣。要以人們以各人的各種感受來描述世界，卻在敘述中忽略這些人的想法和 態度，就好像把菜單當成真正的食物一樣。」也許，未來我們應該用機器人來取代醫 生，並且用機器人取代患者，安慰劑效應才有可能真正的被機器人效應所移除吧。

* Footnotes

[fn:4] Kendrick, Denise, et al. "Radiography of the lumbar spine in primary care patients with low back pain: randomised controlled trial." Bmj 322.7283 (2001): 400-405.

[fn:3] Carvalho, Cláudia, et al. "Open-label placebo treatment in chronic low back pain: a randomized controlled trial." Pain 157.12 (2016): 2766.

[fn:2] Moseley, J. Bruce, et al. "A controlled trial of arthroscopic surgery for osteoarthritis of the knee." New England Journal of Medicine 347.2 (2002): 81-88.

[fn:1] 哈利.柯林斯、崔佛.平區著，李尚仁譯，《科倫醫生吐真言》，左岸文化，2016，頁39
